### CS559 - Homework #3

**Author**: Sid Bhatia

**Date**: October 1st, 2024

**Pledge**: I pledge my honor that I have abided by the Stevens Honor System.

**Professor**: Dr. In Suk Jang

#### 1. Neural Networks [60 pts]

Consider a data point $\mathbf{x} = [0.7, 0.1, 0.3, 0.5]$ and $y = 1.5$. In this experiment, we will implement a simple neural network algorithm. In the lecture, the data point was used to observe the computational process of a neural network with a single hidden layer consisting of two neurons.

a. [5pts] Perform a forward propagation when the network with the one hidden layer of two neurons where $ \mathbf{W}^{(1)} = \begin{bmatrix} 0.16 & 0.02 & 0.63 & 0.36 \\ 0.16 & 0.25 & 0.22 & 0.29 \end{bmatrix} $ and $ \mathbf{W}^{(2)} = \begin{bmatrix} 0.05 \\ 0.33 \end{bmatrix} $. The predicted value $\hat{h}$ should be $0.139$ if the learning rate $\eta = 0.1$ is used. However, it can be changed if needed.

In [14]:
import numpy as np

x = np.array([0.7, 0.1, 0.3, 0.5])

W1 = np.array([
    [0.16, 0.02, 0.63, 0.36],
    [0.16, 0.25, 0.22, 0.29]
])

W2 = np.array([
    [0.05],
    [0.33]
])

z1 = W1.dot(x)
a1 = z1

z2 = W2.T.dot(a1)
h_hat = z2[0]

print(f"Predicted value h_hat = {h_hat:.3f}")

Predicted value h_hat = 0.139


b. [5 pts] Perform the backpropagation. Report the updated $\mathbf{W}^{(1)}$ and $\mathbf{W}^{(2)}$.

In [17]:
y = 1.5

eta = 0.1

delta_output = h_hat - y

dE_dW2 = delta_output * a1

delta_hidden = delta_output * W2

dE_dW1 = np.outer(delta_hidden, x)

W2_new = W2 - eta * dE_dW2
W1_new = W1 - eta * dE_dW1

print("\nUpdated W1:")
print(W1_new)

print("\nUpdated W2:")
print(W2_new)


Updated W1:
[[0.16476354 0.02068051 0.63204152 0.36340252]
 [0.19143933 0.25449133 0.233474   0.31245666]]

Updated W2:
[[0.11573678 0.09736315]
 [0.39573678 0.37736315]]


c. [10pts] Repeat the forward and backpropagation to optimize $\mathbf{W}^{(1)}$ and $\mathbf{W}^{(2)}$. Predict $y$ using the optimized $\mathbf{W}^{(1)}$ and $\mathbf{W}^{(2)}$.

d. [10pts] Consider the same network as (c) except that a non-linear activation is applied. Derive analytical solution of the error matrices, $\bm{\delta}^{(2)}$ and $\bm{\delta}^{(1)}$, when a sigmoid function is applied as a non-linear activation function between the input and hidden layers.

e. [15pts] Predict $y$ for (d). Visualize the convergence of error and compare it to the result in (c). Explain which one converged faster.