### CS559 - Homework #3

**Author**: Sid Bhatia

**Date**: October 1st, 2024

**Pledge**: I pledge my honor that I have abided by the Stevens Honor System.

**Professor**: Dr. In Suk Jang

#### 1. Neural Networks [60 pts]

Consider a data point $\mathbf{x} = [0.7, 0.1, 0.3, 0.5]$ and $y = 1.5$. In this experiment, we will implement a simple neural network algorithm. In the lecture, the data point was used to observe the computational process of a neural network with a single hidden layer consisting of two neurons.

a. [5pts] Perform a forward propagation when the network with the one hidden layer of two neurons where $ \mathbf{W}^{(1)} = \begin{bmatrix} 0.16 & 0.02 & 0.63 & 0.36 \\ 0.16 & 0.25 & 0.22 & 0.29 \end{bmatrix} $ and $ \mathbf{W}^{(2)} = \begin{bmatrix} 0.05 \\ 0.33 \end{bmatrix} $. The predicted value $\hat{h}$ should be $0.139$ if the learning rate $\eta = 0.1$ is used. However, it can be changed if needed.

In [7]:
import numpy as np

x = np.array([0.7, 0.1, 0.3, 0.5])

W1 = np.array([
    [0.16, 0.02, 0.63, 0.36],
    [0.16, 0.25, 0.22, 0.29]
])

W2 = np.array([
    [0.05],
    [0.33]
])

def relu(z):
    return np.maximum(0, z)

z1 = W1.dot(x)

a1 = relu(z1)

z2 = W2.T.dot(a1)

predicted_value = z2[0]

print(f"Predicted value h_hat: {predicted_value:.3f}")

Predicted value h_hat: 0.139


b. [5 pts] Perform the backpropagation. Report the updated $\mathbf{W}^{(1)}$ and $\mathbf{W}^{(2)}$.

In [11]:
y = 1.5

eta = 0.1

def relu_derivative(z):
    return (z > 0).astype(float)

loss = 0.5 * (predicted_value - y) ** 2

delta_output = predicted_value - y

gradient_W2 = delta_output * a1.reshape(-1, 1)

delta_hidden = (W2.flatten() * delta_output) * relu_derivative(z1)

gradient_W1 = delta_hidden.reshape(-1, 1) * x.reshape(1, -1)

W2_updated = W2 - eta * gradient_W2
W1_updated = W1 - eta * gradient_W1

print("Updated W^(1):")
print(W1_updated)
print("\nUpdated W^(2):")
print(W2_updated)

Updated W^(1):
[[0.16476354 0.02068051 0.63204152 0.36340252]
 [0.19143933 0.25449133 0.233474   0.31245666]]

Updated W^(2):
[[0.11573678]
 [0.37736315]]
